server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/company_utility_db
    username: dev_admin
    password: dev_admin
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/realms/company-utility/protocol/openid-connects/certs
          issuer-uri: http://localhost:9000/realms/company-utility
          audiences:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: test
      client-secret: test
      realm: test
      app-name: test